/**
 * Generates MDX API reference pages from the SDK TypeScript sources using TypeDoc.
 *
 * Run: npm run generate:api-docs  (from apps/docs)
 *
 * Output: pages/api-reference/{core,react,elements}.mdx
 * These files are committed to the repo; CI fails if they drift from source.
 */

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '../../..');
const DOCS_DIR = resolve(import.meta.dirname, '..');

// Resolve the typedoc binary through node's resolution — handles workspace hoisting
const require = createRequire(import.meta.url);
function resolveTypedocBin(): string {
  // Walk up from docs dir looking for typedoc in node_modules/.bin
  let dir = DOCS_DIR;
  for (let i = 0; i < 5; i++) {
    const candidate = join(dir, 'node_modules/.bin/typedoc');
    if (existsSync(candidate)) return candidate;
    dir = resolve(dir, '..');
  }
  // Fallback: rely on PATH
  return 'typedoc';
}
const OUT_DIR = join(DOCS_DIR, 'pages/api-reference');
const TYPEDOC_TMP = join(DOCS_DIR, '.typedoc-out');

interface PackageDef {
  name: string;
  slug: string;
  entryPoint: string;
  tsconfig: string;
}

const PACKAGES: PackageDef[] = [
  {
    name: '@pacto-connect/core',
    slug: 'core',
    entryPoint: join(ROOT, 'packages/connect-core/src/index.ts'),
    tsconfig: join(ROOT, 'packages/connect-core/tsconfig.json'),
  },
  {
    name: '@pacto-connect/react',
    slug: 'react',
    entryPoint: join(ROOT, 'packages/connect-react/src/index.ts'),
    tsconfig: join(ROOT, 'packages/connect-react/tsconfig.json'),
  },
  {
    name: '@pacto-connect/elements',
    slug: 'elements',
    entryPoint: join(ROOT, 'packages/connect-elements/src/index.ts'),
    tsconfig: join(ROOT, 'packages/connect-elements/tsconfig.json'),
  },
];

const GENERATED_BANNER = `{/* This file is auto-generated by scripts/generate-api-docs.mts — do not edit by hand. */}
{/* Regenerate: npm run generate:api-docs  (from apps/docs) */}

`;

function ensureDir(dir: string): void {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function runTypedoc(pkg: PackageDef): string {
  const tmpOut = join(TYPEDOC_TMP, pkg.slug);
  ensureDir(tmpOut);

  const args = [
    `--plugin typedoc-plugin-markdown`,
    `--entryPoints "${pkg.entryPoint}"`,
    `--tsconfig "${pkg.tsconfig}"`,
    `--out "${tmpOut}"`,
    `--readme none`,
    `--githubPages false`,
    `--hidePageHeader true`,
    `--hideBreadcrumbs true`,
    `--useCodeBlocks true`,
    `--expandObjects true`,
    `--parametersFormat table`,
    `--propertiesFormat table`,
    `--typeDeclarationFormat table`,
    `--outputFileStrategy members`,
    `--flattenOutputFiles true`,
  ].join(' ');

  const typedocBin = resolveTypedocBin();
  execSync(`${typedocBin} ${args}`, {
    cwd: DOCS_DIR,
    stdio: 'pipe',
  });

  // Collect all generated .md files and concatenate them
  const files = readdirSync(tmpOut)
    .filter((f) => f.endsWith('.md') && f !== 'README.md')
    .sort();

  const parts: string[] = [];
  for (const file of files) {
    const content = readFileSync(join(tmpOut, file), 'utf8');
    parts.push(content);
  }

  return parts.join('\n\n---\n\n');
}

function buildMdxFrontmatter(pkg: PackageDef): string {
  return `---\ntitle: '${pkg.name}'\n---\n\nimport { Callout } from 'nextra/components'\n\n`;
}

function buildCallout(pkg: PackageDef): string {
  return (
    `<Callout type="info">\n` +
    `  This file is auto-generated by \`scripts/generate-api-docs.mts\`. Do not edit by hand.\n` +
    `  Run \`npm run generate:api-docs\` in \`apps/docs\` to refresh it.\n` +
    `</Callout>\n\n`
  );
}

function buildPackageInstall(pkg: PackageDef): string {
  return `# ${pkg.name}\n\n\`\`\`bash\nnpm install ${pkg.name}\n\`\`\`\n\n`;
}

// Escape bare custom-element tags (names with hyphens like <pacto-checkout>)
// that appear outside fenced code blocks, so MDX doesn't treat them as JSX.
function escapeCustomElementsOutsideCodeBlocks(md: string): string {
  const parts = md.split(/(```[\s\S]*?```)/g);
  return parts
    .map((part, i) => {
      // Odd indices are code blocks — leave them untouched
      if (i % 2 === 1) return part;
      // Replace < with &lt; on custom-element tags so MDX doesn't parse them as JSX
      return part.replace(/<([a-z][a-z0-9]*(?:-[a-z0-9]+)+)(\s|>|\/)/g, '&lt;$1$2');
    })
    .join('');
}

async function generate(): Promise<void> {
  ensureDir(OUT_DIR);
  ensureDir(TYPEDOC_TMP);

  let hasError = false;

  for (const pkg of PACKAGES) {
    process.stdout.write(`Generating ${pkg.name}… `);

    let mdxBody: string;
    try {
      const raw = runTypedoc(pkg);
      // TypeDoc markdown uses h1 for module name — strip it and reformat for MDX
      mdxBody = raw
        // Remove top-level module h1 that duplicates our own title
        .replace(/^# Module: .+\n\n?/gm, '')
        // TypeDoc emits <a id="..."> anchors — keep them, they work in MDX
        // Ensure internal links stay relative
        .replace(/\[([^\]]+)\]\((?:\.\/)?([^)]+)\.md(#[^)]+)?\)/g, (_, text, file, hash) => {
          // Link within same package page — make it a heading anchor
          return hash ? `[${text}](${hash})` : `[${text}](#${file.toLowerCase()})`;
        });

      // Escape bare custom-element tags (e.g. <pacto-checkout>) outside code blocks
      // so MDX doesn't try to parse them as JSX components.
      mdxBody = escapeCustomElementsOutsideCodeBlocks(mdxBody);

      const outContent =
        GENERATED_BANNER +
        buildMdxFrontmatter(pkg) +
        buildCallout(pkg) +
        buildPackageInstall(pkg) +
        mdxBody;

      const outPath = join(OUT_DIR, `${pkg.slug}.mdx`);
      writeFileSync(outPath, outContent, 'utf8');
      console.log('✓');
    } catch (err) {
      console.log('✗');
      console.error(`  Error generating ${pkg.name}:`, err instanceof Error ? err.message : err);
      hasError = true;
    }
  }

  // Cleanup temp dir
  try {
    execSync(`rm -rf "${TYPEDOC_TMP}"`);
  } catch {
    // non-fatal
  }

  if (hasError) {
    process.exit(1);
  }

  console.log('\nAPI docs generated successfully.');
  console.log(`  Output: ${OUT_DIR}`);
}

await generate();
